interface AdministrativeDivision {
  parent: string;
  parentId: number;
  id: number;
  name: string;
  type: string;
}

const administrativeDivisions: AdministrativeDivision[] = [
  {
    parent: "11000 - УЛААНБААТАР",
    parentId: 2586,
    id: 24,
    name: "БАГАХАНГАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "11000 - УЛААНБААТАР",
    parentId: 2586,
    id: 25,
    name: "НАЛАЙХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "11000 - УЛААНБААТАР",
    parentId: 2586,
    id: 26,
    name: "БАЯНЗҮРХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "11000 - УЛААНБААТАР",
    parentId: 2586,
    id: 27,
    name: "СҮХБААТАР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "11000 - УЛААНБААТАР",
    parentId: 2586,
    id: 28,
    name: "ЧИНГЭЛТЭЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "11000 - УЛААНБААТАР",
    parentId: 2586,
    id: 29,
    name: "БАЯНГОЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "11000 - УЛААНБААТАР",
    parentId: 2586,
    id: 30,
    name: "ХАН-УУЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "11000 - УЛААНБААТАР",
    parentId: 2586,
    id: 31,
    name: "СОНГИНОХАЙРХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 32,
    name: "ХАЛХГОЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 33,
    name: "МАТАД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 34,
    name: "ЧУЛУУНХОРООТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 35,
    name: "ЧОЙБАЛСАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 36,
    name: "БАЯНТҮМЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 37,
    name: "ХЭРЛЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 38,
    name: "ГУРВАНЗАГАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 39,
    name: "БУЛГАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 40,
    name: "ДАШБАЛБАР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 41,
    name: "СЭРГЭЛЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 42,
    name: "БАЯНДУН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 43,
    name: "ЦАГААН-ОВОО",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 44,
    name: "ХӨЛӨНБУЙР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "21000 - ДОРНОД",
    parentId: 2,
    id: 45,
    name: "БАЯН-УУЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 46,
    name: "ЭРДЭНЭЦАГААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 47,
    name: "СҮХБААТАР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 48,
    name: "ДАРЬГАНГА",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 49,
    name: "АСГАТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 50,
    name: "НАРАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 51,
    name: "БАРУУН-УРТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 52,
    name: "ОНГОН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 53,
    name: "ХАЛЗАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 54,
    name: "БАЯНДЭЛГЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 55,
    name: "УУЛБАЯН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 56,
    name: "МӨНХХААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 57,
    name: "ТҮМЭНЦОГТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "22000 - СҮХБААТАР",
    parentId: 3,
    id: 58,
    name: "ТҮВШИНШИРЭЭ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 59,
    name: "БАЯН-ОВОО",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 60,
    name: "ДАДАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 61,
    name: "НОРОВЛИН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 62,
    name: "БАТНОРОВ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 63,
    name: "БАЯН-ХУТАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 64,
    name: "БАЯН-АДАРГА",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 65,
    name: "ГАЛШИР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 66,
    name: "БИНДЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 67,
    name: "ХЭРЛЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 68,
    name: "МӨРӨН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 69,
    name: "ӨМНӨДЭЛГЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 70,
    name: "БАТШИРЭЭТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 71,
    name: "БАЯНМӨНХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 72,
    name: "ДАРХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 73,
    name: "ЖАРГАЛТХААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 74,
    name: "ДЭЛГЭРХААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "23000 - ХЭНТИЙ",
    parentId: 4,
    id: 75,
    name: "ЦЭНХЭРМАНДАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 76,
    name: "МӨНГӨНМОРЬТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 77,
    name: "БАЯНЖАРГАЛАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 78,
    name: "БАЯНДЭЛГЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 79,
    name: "ЭРДЭНЭ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 80,
    name: "АРХУСТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 81,
    name: "БАЯН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 82,
    name: "БАЯНЦАГААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 83,
    name: "СЭРГЭЛЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 84,
    name: "ЗУУНМОД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 85,
    name: "БАТСҮМБЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 86,
    name: "АЛТАНБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 87,
    name: "БАЯН-ӨНЖҮҮЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 88,
    name: "БОРНУУР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 89,
    name: "БАЯНЧАНДМАНЬ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 90,
    name: "БАЯНЦОГТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 91,
    name: "АРГАЛАНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 92,
    name: "СҮМБЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 93,
    name: "ЖАРГАЛАНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 94,
    name: "БАЯНХАНГАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 95,
    name: "УГТААЛЦАЙДАМ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 96,
    name: "ЦЭЭЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 97,
    name: "ЛҮН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 98,
    name: "ӨНДӨРШИРЭЭТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 99,
    name: "БҮРЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 100,
    name: "ЗААМАР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 101,
    name: "ДЭЛГЭРХААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "41000 - ТӨВ",
    parentId: 5,
    id: 102,
    name: "ЭРДЭНЭСАНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "42000 - ГОВЬСҮМБЭР",
    parentId: 7,
    id: 103,
    name: "СҮМБЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "42000 - ГОВЬСҮМБЭР",
    parentId: 7,
    id: 104,
    name: "ШИВЭЭГОВЬ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "42000 - ГОВЬСҮМБЭР",
    parentId: 7,
    id: 105,
    name: "БАЯНТАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 106,
    name: "ЗАМЫН-ҮҮД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 107,
    name: "ЭРДЭНЭ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 108,
    name: "ӨРГӨН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 109,
    name: "ДЭЛГЭРЭХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 110,
    name: "УЛААНБАДРАХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 111,
    name: "ХӨВСГӨЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 112,
    name: "АЛТАНШИРЭЭ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 113,
    name: "ХАТАНБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 114,
    name: "ИХХЭТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 115,
    name: "САЙНШАНД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 116,
    name: "САЙХАНДУЛААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 117,
    name: "АЙРАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 118,
    name: "ДАЛАНЖАРГАЛАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "44000 - ДОРНОГОВЬ",
    parentId: 8,
    id: 119,
    name: "МАНДАХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "45000 - ДАРХАН-УУЛ",
    parentId: 10,
    id: 120,
    name: "ШАРЫН ГОЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "45000 - ДАРХАН-УУЛ",
    parentId: 10,
    id: 121,
    name: "ХОНГОР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "45000 - ДАРХАН-УУЛ",
    parentId: 10,
    id: 122,
    name: "ОРХОН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "45000 - ДАРХАН-УУЛ",
    parentId: 10,
    id: 123,
    name: "ДАРХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 124,
    name: "ӨНДӨРШИЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 125,
    name: "БАЯНЖАРГАЛАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 126,
    name: "ЦАГААНДЭЛГЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 127,
    name: "ӨЛЗИЙТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 128,
    name: "ГУРВАНСАЙХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 129,
    name: "ГОВЬ-УГТААЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 130,
    name: "ДЭРЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 131,
    name: "САЙНЦАГААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 132,
    name: "ДЭЛГЭРЦОГТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 133,
    name: "ЛУУС",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 134,
    name: "ХУЛД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 135,
    name: "АДААЦАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 136,
    name: "ЭРДЭНЭДАЛАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 137,
    name: "ДЭЛГЭРХАНГАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "48000 - ДУНДГОВЬ",
    parentId: 11,
    id: 138,
    name: "САЙХАН-ОВОО",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 139,
    name: "ЕРӨӨ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 140,
    name: "ХҮДЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 141,
    name: "МАНДАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 142,
    name: "АЛТАНБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 143,
    name: "ЖАВХЛАНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 144,
    name: "БАЯНГОЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 145,
    name: "ШААМАР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 146,
    name: "СҮХБААТАР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 147,
    name: "ЗҮҮНБҮРЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 148,
    name: "ТҮШИГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 149,
    name: "ЦАГААННУУР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 150,
    name: "ХУШААТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 151,
    name: "САЙХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 152,
    name: "ОРХОН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 153,
    name: "САНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 154,
    name: "ОРХОНТУУЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "43000 - СЭЛЭНГЭ",
    parentId: 6,
    id: 155,
    name: "БАРУУНБҮРЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 156,
    name: "ХАНБОГД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 157,
    name: "МАНЛАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 158,
    name: "БАЯН-ОВОО",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 159,
    name: "ЦОГТЦЭЦИЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 160,
    name: "НОМГОН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 161,
    name: "ЦОГТ-ОВОО",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 162,
    name: "ХАНХОНГОР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 163,
    name: "ДАЛАНЗАДГАД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 164,
    name: "МАНДАЛ-ОВОО",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 165,
    name: "ХҮРМЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 166,
    name: "БУЛГАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 167,
    name: "БАЯНДАЛАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 168,
    name: "СЭВРЭЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 169,
    name: "НОЁН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "46000 - ӨМНӨГОВЬ",
    parentId: 9,
    id: 170,
    name: "ГУРВАНТЭС",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "61000 - ОРХОН",
    parentId: 12,
    id: 171,
    name: "ЖАРГАЛАНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "61000 - ОРХОН",
    parentId: 12,
    id: 172,
    name: "БАЯН-ӨНДӨР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 173,
    name: "БАЯН-ӨНДӨР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 174,
    name: "БҮРД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 175,
    name: "ЕСӨНЗҮЙЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 176,
    name: "САНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 177,
    name: "ӨЛЗИЙТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 178,
    name: "БАЯНГОЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 179,
    name: "ТӨГРӨГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 180,
    name: "ХАРХОРИН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 181,
    name: "ХУЖИРТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 182,
    name: "ЗҮҮНБАЯН-УЛААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 183,
    name: "ТАРАГТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 184,
    name: "АРВАЙХЭЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 185,
    name: "ГУЧИН-УС",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 186,
    name: "БОГД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 187,
    name: "БАТ-ӨЛЗИЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 188,
    name: "УЯНГА",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 189,
    name: "ХАЙРХАНДУЛААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 190,
    name: "НАРИЙНТЭЭЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "62000 - ӨВӨРХАНГАЙ",
    parentId: 13,
    id: 191,
    name: "БАРУУНБАЯН-УЛАА",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 192,
    name: "БАЯННУУР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 193,
    name: "СЭЛЭНГЭ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 194,
    name: "ХАНГАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 195,
    name: "ОРХОН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 196,
    name: "БҮРЭГХАНГАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 197,
    name: "ДАШИНЧИЛЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 198,
    name: "РАШААНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 199,
    name: "БУЛГАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 200,
    name: "БУГАТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 201,
    name: "ТЭШИГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 202,
    name: "ХИШИГ-ӨНДӨР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 203,
    name: "ГУРВАНБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 204,
    name: "ХУТАГ-ӨНДӨР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 205,
    name: "МОГОД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 206,
    name: "САЙХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "63000 - БУЛГАН",
    parentId: 15,
    id: 207,
    name: "БАЯН-АГТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 208,
    name: "ХАШААТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 209,
    name: "ӨГИЙНУУР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 210,
    name: "ӨЛЗИЙТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 211,
    name: "ХОТОНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 212,
    name: "ХАЙРХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 213,
    name: "ТӨВШРҮҮЛЭХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 214,
    name: "ЦЭНХЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 215,
    name: "БАТЦЭНГЭЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 216,
    name: "БУЛГАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 217,
    name: "ЭРДЭНЭБУЛГАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 218,
    name: "ЭРДЭНЭМАНДАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 219,
    name: "ИХ ТАМИР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 220,
    name: "ЦЭЦЭРЛЭГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 221,
    name: "ТАРИАЛАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 222,
    name: "ЭРДЭНЭБУЛГАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 223,
    name: "ЦАГААН-ҮҮР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 224,
    name: "ИХ-УУЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 225,
    name: "РАШААНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 226,
    name: "ХАНХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 227,
    name: "ЧАНДМАНЬ-ӨНДӨР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 228,
    name: "ТҮНЭЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 229,
    name: "ТОСОНЦЭНГЭЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 230,
    name: "МӨРӨН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 231,
    name: "АЛАГ-ЭРДЭНЭ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 232,
    name: "ТӨМӨРБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 233,
    name: "РЭНЧИНЛХҮМБЭ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 234,
    name: "ГАЛТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 235,
    name: "АРБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 236,
    name: "БҮРЭНТОГТОХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 237,
    name: "ШИНЭ-ИДЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 238,
    name: "ЖАРГАЛАНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 239,
    name: "ЦАГААННУУР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 240,
    name: "УЛААН-УУЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 241,
    name: "БАЯНЗҮРХ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 242,
    name: "ЦАГААН-УУЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "67000 - ХӨВСГӨЛ",
    parentId: 14,
    id: 243,
    name: "ЦЭЦЭРЛЭГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 244,
    name: "БАЯНЛИГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 245,
    name: "ЭРДЭНЭЦОГТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 246,
    name: "ӨЛЗИЙТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 247,
    name: "БОГД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 248,
    name: "ЖИНСТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 249,
    name: "БАЯН-ОВОО",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 250,
    name: "БАЯНХОНГОР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 251,
    name: "ГАЛУУТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 252,
    name: "БАЯНГОВЬ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 253,
    name: "БААЦАГААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 254,
    name: "БӨМБӨГӨР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 255,
    name: "ЖАРГАЛАНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 256,
    name: "ШИНЭЖИНСТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 257,
    name: "ЗАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 258,
    name: "БАЯНЦАГААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 259,
    name: "БУУЦАГААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 260,
    name: "ГУРВАНБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 261,
    name: "ХҮРЭЭМАРАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 262,
    name: "БАЯН-ӨНДӨР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "64000 - БАЯНХОНГОР",
    parentId: 16,
    id: 263,
    name: "БАЯНБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 264,
    name: "ЖАРГАЛАНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 265,
    name: "ӨНДӨР-УЛААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 266,
    name: "ЧУЛУУТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 267,
    name: "ТАРИАТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 268,
    name: "ХАНГАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "65000 - АРХАНГАЙ",
    parentId: 17,
    id: 269,
    name: "ЦАХИР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 270,
    name: "ИХ-УУЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 271,
    name: "ТОСОНЦЭНГЭЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 272,
    name: "ТЭЛМЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 273,
    name: "ИДЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 274,
    name: "ОТГОН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 275,
    name: "УЛИАСТАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 276,
    name: "НӨМРӨГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 277,
    name: "ЦАГААНХАЙРХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 278,
    name: "ЯРУУ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 279,
    name: "ШИЛҮҮСТЭЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 280,
    name: "ЦАГААНЧУЛУУТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 281,
    name: "БАЯНТЭС",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 282,
    name: "АСГАТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 283,
    name: "БАЯНХАЙРХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 284,
    name: "АЛДАРХААН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 285,
    name: "ТҮДЭВТЭЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 286,
    name: "ЦЭЦЭН-УУЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 287,
    name: "СОНГИНО",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 288,
    name: "ЭРДЭНЭХАЙРХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 289,
    name: "ТЭС",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 290,
    name: "САНТМАРГАЦ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 291,
    name: "ЗАВХАНМАНДАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 292,
    name: "ДӨРВӨЛЖИН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "81000 - ЗАВХАН",
    parentId: 18,
    id: 293,
    name: "УРГАМАЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 294,
    name: "ДЭЛГЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 295,
    name: "ЧАНДМАНЬ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 296,
    name: "ЭРДЭНЭ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 297,
    name: "БИГЭР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 298,
    name: "ЦОГТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 299,
    name: "ТАЙШИР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 300,
    name: "ЕСӨНБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 301,
    name: "ХАЛИУН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 302,
    name: "ЖАРГАЛАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 303,
    name: "ЦЭЭЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 304,
    name: "АЛТАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 305,
    name: "ШАРГА",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 306,
    name: "БАЯН-УУЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 307,
    name: "ТӨГРӨГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 308,
    name: "ХӨХМОРЬТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 309,
    name: "ДАРВИ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 310,
    name: "БУГАТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "82000 - ГОВЬ-АЛТАЙ",
    parentId: 21,
    id: 311,
    name: "ТОНХИЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 312,
    name: "ЗҮҮНХАНГАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 313,
    name: "БАРУУНТУРУУН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 314,
    name: "ӨНДӨРХАНГАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 315,
    name: "ЗҮҮНГОВЬ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 316,
    name: "ЦАГААНХАЙРХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 317,
    name: "ТЭС",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 318,
    name: "ХЯРГАС",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 319,
    name: "МАЛЧИН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 320,
    name: "ЗАВХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 321,
    name: "НАРАНБУЛАГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 322,
    name: "ДАВСТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 323,
    name: "ТАРИАЛАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 324,
    name: "ӨЛГИЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 325,
    name: "УЛААНГОМ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 326,
    name: "САГИЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 327,
    name: "ТҮРГЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 328,
    name: "ӨМНӨГОВЬ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 329,
    name: "БӨХМӨРӨН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "85000 - УВС",
    parentId: 19,
    id: 330,
    name: "ХОВД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 331,
    name: "ДАРВИ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 332,
    name: "ДӨРГӨН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 333,
    name: "ЧАНДМАНЬ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 334,
    name: "ЦЭЦЭГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 335,
    name: "ЗЭРЭГ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 336,
    name: "МӨСТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 337,
    name: "АЛТАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 338,
    name: "БУЯНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 339,
    name: "МЯНГАД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 340,
    name: "МАНХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 341,
    name: "ҮЕНЧ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 342,
    name: "ЖАРГАЛАНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 343,
    name: "ХОВД",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 344,
    name: "ЭРДЭНЭБҮРЭН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 345,
    name: "МӨНХХАЙРХАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 346,
    name: "ДУУТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "84000 - ХОВД",
    parentId: 20,
    id: 347,
    name: "БУЛГАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 348,
    name: "БУЛГАН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 349,
    name: "БАЯННУУР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 350,
    name: "АЛТАНЦӨГЦ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 351,
    name: "БУГАТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 352,
    name: "ДЭЛҮҮН",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 353,
    name: "ТОЛБО",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 354,
    name: "НОГООННУУР",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 355,
    name: "ӨЛГИЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 356,
    name: "БУЯНТ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 357,
    name: "АЛТАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 358,
    name: "САГСАЙ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 359,
    name: "УЛААНХУС",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "83000 - БАЯН-ӨЛГИЙ",
    parentId: 22,
    id: 360,
    name: "ЦЭНГЭЛ",
    type: "Сум / Дүүрэг",
  },
  {
    parent: "11000 - УЛААНБААТАР",
    parentId: 2586,
    id: 2598,
    name: "БАГАНУУР",
    type: "Сум / Дүүрэг",
  },
];

export type { AdministrativeDivision };
export { administrativeDivisions };
