import { FormValues } from "@/types/form";

export const initialFormValues: FormValues = {
  accidentPhotos: [],
  insuranceContractPhotos: [],
  invoicedAmount: 0,
  driverPhotos: [],
  policePhotos: [], // Цагдааны зураг
  startDate: "",
  phone: "",
  mail: "",
  endDate: "",
  plateNumber: "",
  xplateNumber: "",
  contractNumber: "",
  ownerRegister: "",
  serialNumber: "",
  isValid: "",
  registerPart: "",
  contractId: "",
  driverImage: null,
  policeCalled: 0,
  accidentCalled: 0,
  caseDate: "",
  victimPhone: "",
  caseCityId: 11,
  caseDistrictId: 22,
  caseLocation: "",
  caseDescription: "",
  driverName: "",
  driverLastname: "",
  driverRegNum: "",
  driverPhone: "",
  driverBankId: 0,
  driverBankAccount: "",
  driverBankAccountName: "",
  bankAccountLastname: "",
  bankAccountRegnum: "",
  victimName: "",
  victimLastname: "",
  victimRegNum: "",
  inspected: 0,
  insurerAgreement: 0,
  agreementAmount: "",
  attachments: [],
  homeAddress: "",
  homeCityId: 0,
  homeDistrictId: 0,
  contractProductName: "",
};
