const deepLinks = [
  // {
  //   name: "qPay wallet",
  //   description: "qPay хэтэвч",
  //   logo: "https://s3.qpay.mn/p/e9bbdc69-3544-4c2f-aff0-4c292bc094f6/launcher-icon-ios.jpg",
  //   link: "qpaywallet://q?qPay_QRcode=",
  //   id: 0,
  // },
  {
    name: "Khan bank",
    description: "Хаан банк",
    logo: "https://qpay.mn/q/logo/khanbank.png",
    link: "khanbank://q?qPay_QRcode=",
    id: 6,
  },
  {
    name: "State bank 3.0",
    description: "Төрийн банк 3.0",
    logo: "https://qpay.mn/q/logo/state_3.png",
    link: "statebankmongolia://q?qPay_QRcode=",
    id: 14,
  },
  {
    name: "Xac bank",
    description: "Хас банк",
    logo: "https://qpay.mn/q/logo/xacbank.png",
    link: "xacbank://q?qPay_QRcode=",
    id: 12,
  },
  {
    name: "Trade and Development bank",
    description: "Худалдаа хөгжлийн банк",
    logo: "https://qpay.mn/q/logo/tdbbank.png",
    link: "tdbbank://q?qPay_QRcode=",
    id: 5,
  },
  {
    name: "Голомт SocialPay",
    description: "Голомт банк",
    logo: "https://qpay.mn/q/logo/socialpay.png",
    link: "socialpay-payment://q?qPay_QRcode=",
    id: 31,
  },
  // {
  //   name: "Most money",
  //   description: "МОСТ мони",
  //   logo: "https://qpay.mn/q/logo/most.png",
  //   link: "most://q?qPay_QRcode=",
  //   id: 0,
  // },
  {
    name: "National investment bank",
    description: "Үндэсний хөрөнгө оруулалтын банк",
    logo: "https://qpay.mn/q/logo/nibank.jpeg",
    link: "nibank://q?qPay_QRcode=",
    id: 10,
  },
  {
    name: "Chinggis khaan bank",
    description: "Чингис Хаан банк",
    logo: "https://qpay.mn/q/logo/ckbank.png",
    link: "ckbank://q?qPay_QRcode=",
    id: 13,
  },
  {
    name: "Capitron bank",
    description: "Капитрон банк",
    logo: "https://qpay.mn/q/logo/capitronbank.png",
    link: "capitronbank://q?qPay_QRcode=",
    id: 11,
  },
  {
    name: "Bogd bank",
    description: "Богд банк",
    logo: "https://qpay.mn/q/logo/bogdbank.png",
    link: "bogdbank://q?qPay_QRcode=",
    id: 16,
  },
  {
    name: "Trans bank",
    description: "Тээвэр хөгжлийн банк",
    logo: "https://qpay.mn/q/logo/transbank.png",
    link: "transbank://q?qPay_QRcode=",
    id: 7,
  },
  {
    name: "M bank",
    description: "М банк",
    logo: "https://qpay.mn/q/logo/mbank.png",
    link: "mbank://q?qPay_QRcode=",
    id: 73,
  },
  {
    name: "Ard App",
    description: "Ард Кредит",
    logo: "https://qpay.mn/q/logo/ardapp.png",
    link: "ard://q?qPay_QRcode=",
    id: 82,
  },
  {
    name: "Arig bank",
    description: "Ариг банк",
    logo: "https://qpay.mn/q/logo/arig.png",
    link: "arig://q?qPay_QRcode=",
    id: 8,
  },
  // {
  //   name: "Monpay",
  //   description: "Мон Пэй",
  //   logo: "https://qpay.mn/q/logo/monpay.png",
  //   link: "Monpay://q?qPay_QRcode=",
  //   id: 0,
  // },
  {
    name: "Capital bank",
    description: "Капитал банк",
    logo: "https://qpay.mn/q/logo/capitalbank.png",
    link: "capitalbank://q?qPay_QRcode=",
    id: 34,
  },
  {
    name: "Credit bank",
    description: "Кредит банк",
    logo: "https://qpay.mn/q/logo/creditbank.png",
    link: "creditbank://q?qPay_QRcode=",
    id: 9,
  },
  {
    name: "Central bank",
    description: "Төв банк",
    logo: "https://qpay.mn/q/logo/centralbank.png",
    link: "centralbank://q?qPay_QRcode=",
    id: 4,
  },
  {
    name: "Ulaanbaatar city bank",
    description: "Улаанбаатар хотын банк",
    logo: "https://qpay.mn/q/logo/ubcbank.png",
    link: "ubcbank://q?qPay_QRcode=",
    id: 32,
  },
  {
    name: "Savings bank",
    description: "Хадгаламж банк",
    logo: "https://qpay.mn/q/logo/savingsbank.png",
    link: "savingsbank://q?qPay_QRcode=",
    id: 33,
  },
  // {
  //   name: "Hi payment solution",
  //   description: "Хай Пэймэнт Солюшин ХХК",
  //   logo: "https://qpay.mn/q/logo/hipayment.png",
  //   link: "hipayment://q?qPay_QRcode=",
  //   id: 61,
  // },
  {
    name: "Development bank",
    description: "Хөгжлийн банк",
    logo: "https://qpay.mn/q/logo/developmentbank.png",
    link: "developmentbank://q?qPay_QRcode=",
    id: 15,
  },
];

export default deepLinks;
